### ISSUE TITLE
ImportError: cannot import name 'itea_srbench' from 'ITEA'

### ISSUE THREAD

**Issue by hengzhe-zhang** [cavalab/srbench#144]
I attempted to run ITEA within a Docker image; however, I encountered an error. I suspect that the issue arises from recent refactoring in ITEA. It would be greatly appreciated if you could update the relevant code in srbench or adjust the Git version in the [ITEA installation script](https://github.com/cavalab/srbench/blob/master/experiment/methods/src/itea_install.sh).

```python
Traceback (most recent call last):
  File "ITEARegressor.py", line 1, in <module>
    from ITEA import itea_srbench as itea
ImportError: cannot import name 'itea_srbench' from 'ITEA' (unknown location)
```

**Comment by folivetti** [comment]
hi @hengzhe-zhang could you send me the output of the installation proccess? (i.e., the output when running itea_install.sh)

**Comment by hengzhe-zhang** [comment]
I did not install it myself. I used the docker image.

**Comment by folivetti** [comment]
gonna check that on my machine and I'll let you know.

**Comment by hengzhe-zhang** [comment]
I used this command to install the docker image.

```bash
docker build --pull --rm -f "Dockerfile" -t srbench:latest "."
```

**Comment by folivetti** [comment]
have you changed anything before running this command? Cloning the repo and running this doesn't work for me (i.e., gives errors unrelated to itea)

**Comment by hengzhe-zhang** [comment]
> have you changed anything before running this command? Cloning the repo and running this doesn't work for me (i.e., gives errors unrelated to itea)

No. The docker image is ready to use out of the box.

**Comment by hengzhe-zhang** [comment]
No problem!

```yaml
name: srbench
channels:
    - conda-forge
dependencies:
    - make
    - compilers
    - python
    - cmake=3.19.1 # operon, feat
    - eigen=3.3.9 # operon, feat, ellyn
    - boost=1.74.0 # gpgomea, ellyn
    - pkg-config # gpgomea
    - scikit-learn=0.24.1
    - pyarrow
    - pandas
    - numpy
    - xgboost
    - lightgbm
    - gplearn
    - armadillo=9.900.4 # gpgomea
    - jupyter
    - pytest
    - matplotlib
    # operon
    - pybind11=2.6.1
    - fmt=7.1.3
    - taskflow=3.3.0
    - xxhash
    #deep-symbolic-regression
    - tensorflow=1.14
    - cython
    - numba
    - sympy
    - click
    - mpi4py
    - dataclasses
    # itea
    # - libblas=3.9.0=8_openblas
    # - liblapack=3.9.0=8_openblas
    # - gmp=6.2.1=h58526e2_0
    # - gsl=2.6=he838d99_2
    # - libffi=3.3=h58526e2_2
    # feat
    - cython=0.29.*
    - ninja
    - setuptools=45.*
    - shogun-cpp=6.1.4
    - wheel=0.35.*
    # PySR:
    - julia # Note that this is julia itself.
    - openlibm
    # pip
    - pip=20.3.3
    - pip:
        - DistanceClassifier==0.0.8 # ellyn
        - pmlb==1.0.1.post3
        - ffx==2.0.2 # ffx
        - eigency==1.77
        # BSR
        - git+https://github.com/lacava/MCMC-SymReg
        # AI-feynman
        - git+https://github.com/lacava/AI-Feynman
        # PySR:
        - julia==0.5.7 # Note that this is PyJulia (pip name julia)
        - pysr==0.7.0a3

```
