### ISSUE TITLE
Use `micromamba` instead of `conda` 

### ISSUE THREAD

**Issue by lacava** [cavalab/srbench#64]
One other suggestion: use `micromamba` instead of `conda` (mamba is a C++ rewrite of conda - it uses the same package servers but is **much** faster). The docker image `mambaorg/micromamba` which has `micromamba` built-in seems to work if all `conda` calls are replaced with `micromamba`. It's much faster for me!

_Originally posted by @MilesCranmer in https://github.com/cavalab/srbench/issues/59#issuecomment-1017641513_

**Comment by MilesCranmer** [comment]
I think mamba can be set up in the GitHub actions with:
```
          use-mamba: true
```
in the `conda-incubator` action. Source: https://github.com/conda-incubator/setup-miniconda#example-10-miniforge.

Once this is done, all that needs to be done is replace all `conda` commands with `mamba`. Maybe it could even be done by setting `alias conda=mamba`. 

Alternatively, all `conda` commands could be replaced by `$(CONDA)` and then you can define any `CONDA` environment variable you'd like.

**Comment by MilesCranmer** [comment]
Two other comments to get more speed:

- The `test.yml` should have each algorithm as part of a build matrix. That way, separate GitHub actions can test each algorithm in parallel. Thus, instead of having a 25 minute job that runs everything, you might have 15 jobs (limit is 25 jobs, so it's fine) which run in parallel for 10 minutes total.

e.g.,
```yaml
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.7.1']
        python-version: ['3.9']
        os: [ubuntu-latest]
        algorithm: ['PySR', 'Operon', ....
```
you would then pass as an argument `${{ matrix.algorithm }}` to your `install.sh` and `test_evaluate_models.py`.


- Turn back on conda caching. Not sure why it is currently turned off but it will probably help get a big speedup, especially if you are running.
